name: Update links

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: cat update script
        run: cat update-freeip.sh
        
      - name: Run update script
        run: bash update-freeip.sh
        
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [[ `git status --porcelain` ]]; then
            git add links.txt
            git commit -m "Auto update links.txt"
            git push
          else
            echo "No changes in links.txt"
          fi
